version: '3'

services:
  flask:
    build: ./src
    container_name: flask_app
    networks:
      - admin
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

networks:
  admin:
    external: true

volumes:
  mongodb_data: